-- MySQL Script generated by MySQL Workbench
-- Tue Apr 25 22:14:51 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_supermercado` DEFAULT CHARACTER SET utf8 ;
USE `db_supermercado` ;

-- -----------------------------------------------------
-- Table `mydb`.`Gestor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_supermercado`.`Gestor` (
  `idGestor` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `documento` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idGestor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_supermercado`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` DOUBLE NOT NULL,
  `Gestor_idGestor` INT NOT NULL,
  PRIMARY KEY (`idProduto`, `Gestor_idGestor`),
  INDEX `fk_Produto_Gestor1_idx` (`Gestor_idGestor` ASC),
  CONSTRAINT `fk_Produto_Gestor1`
    FOREIGN KEY (`Gestor_idGestor`)
    REFERENCES `mydb`.`Gestor` (`idGestor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_supermercado`.`Funcionario` (
  `idFuncionario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `documento` VARCHAR(15) NOT NULL,
  `telefone` INT(20) NOT NULL,
  `senha` VARCHAR(35) NOT NULL,
  `Gestor_idGestor` INT NOT NULL,
  PRIMARY KEY (`idFuncionario`, `Gestor_idGestor`),
  INDEX `fk_Funcionario_Gestor1_idx` (`Gestor_idGestor` ASC),
  CONSTRAINT `fk_Funcionario_Gestor1`
    FOREIGN KEY (`Gestor_idGestor`)
    REFERENCES `mydb`.`Gestor` (`idGestor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_supermercado`.`Venda` (
  `idVenda` INT NOT NULL AUTO_INCREMENT,
  `Produto_idProduto` INT NOT NULL,
  `Funcionario_idFuncionario` INT NOT NULL,
  `Funcionario_Gestor_idGestor` INT NOT NULL,
  `formaPagamento` INT(1) NOT NULL,
  PRIMARY KEY (`idVenda`, `Produto_idProduto`, `Funcionario_idFuncionario`, `Funcionario_Gestor_idGestor`),
  INDEX `fk_Venda_Produto_idx` (`Produto_idProduto` ASC),
  INDEX `fk_Venda_Funcionario1_idx` (`Funcionario_idFuncionario` ASC, `Funcionario_Gestor_idGestor` ASC),
  CONSTRAINT `fk_Venda_Produto`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Funcionario1`
    FOREIGN KEY (`Funcionario_idFuncionario` , `Funcionario_Gestor_idGestor`)
    REFERENCES `mydb`.`Funcionario` (`idFuncionario` , `Gestor_idGestor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
